"""user_update

Revision ID: 920362aa87cb
Revises: 1f600f2f376b
Create Date: 2018-06-21 17:24:29.783423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920362aa87cb'
down_revision = '1f600f2f376b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
